### ISSUE TITLE
Mejoras diversas en la herramienta

### ISSUE THREAD

**Issue by dilworks** [neocarvajal/TR10-TOOL#1]
Antes que nada, saludos, y gracias por la herramienta!
A mis manos llego justamente una TR10RS1 y una TR10CS1 para hacerle "el tratamiento", y lamentablemente todos los tutoriales que conseguía eran para Windows (yo uso Debian, tanto en casa como en el trabajo), y con paquetes e instrucciones que no me generaban mucha confianza. En comparación el tuyo es sencillito, rápido, y seguro (digo, hasta ahora la tableta aun sirve :D)

Pero como hay lugar para mejoras, he aqui algunas sugerencias:

1) ¿Por que usar una versión del SDK de Android (adb y sus amiguis) directo aca? En algunas distros (mejor dicho, en la mayoría), es posible instalarlo directamente desde los repositorios de la distro de turno, y generalmente por mas vieja que sea la versión _tos_Debian_tos_, suele funcionar sin problemas para el propósito. Es mas, para algunos usuarios esto podría generar conflictos, ya que la versión de adb que viene en tu repositorio podría no percatarse de instancias anteriores de la versión de adb en el sistema. También existimos los usuarios de distros de 64 bits sin soporte instalado para correr binarios de 32 (solo instala cualquier Debian/Ubuntu reciente para un buen ejemplo), y seria una sorpresa desagradable para esos usuarios el darse cuenta de que la herramienta no sirve porque el adb que incluyes es de 32 bits. La sugerencia seria indicarle al usuario realizar ese paso extra, y usar el adb del SDK instalado en el sistema, y solo ofrecer descargarlo en caso extremo.

2) Solo son dos modelos (desconozco las diferencias básicas entre ambos, no me he puesto a verlos a fondo, ya después tendré tiempo para eso), asi que asumo que los IDs USB han de ser los mismos - en este caso podrías sugerir un 51-android.rules predeterminado como el siguiente:

```
# TR10RS1
SUBSYSTEM=="usb", ATTRS{idVendor}=="8087",ATTRS{idProduct}=="0a5f", MODE="0666"
# TR10CS1
SUBSYSTEM=="usb", ATTRS{idVendor}=="8087",ATTRS{idProduct}=="0a16", MODE="0666"
```

3) Algunos no gustamos de ver videos instructivos (si, ya se, todavía vivo en 1986 y me encantan los manuales de servicio de 500 paginas...), así que las instrucciones en texto necesitan ampliarse un poco. Por ejemplo, se me paso por alto que podía flashear tanto SuperSu como las GApps en un solo paso ya que... francamente no lo vi. También en otros lados se sugiere que la tableta tenga al menos el 50% de carga de batería antes de intentar todo esto, y me parece una recomendación de seguridad básica que debería apuntarse en las instrucciones.

Nuevamente, gracias por todo tu trabajo!

**Comment by neocarvajal** [comment]
Gracias por tomarte el tiempo en escribir todas tus recomendaciones, aquí algunas cosas a tener en cuenta :

1) ¿Por que usar una versión del SDK de Android (adb y sus amiguis) ? 

Una de las razones por la que decidí incluir en proyecto las herramientas "PlatformTools" de SDK es que los usuarios no necesitan instalar nada en su sistema operativo para poder usar la herramienta, creando como una dependencia innecesaria.  

Otra razón súper importante es que cuando tenia instalado ADB y FASTBOOT tenia problemas para que la tablet en modo "DroidBoot" reconociera los comandos fastboot para la pc.

 la siguiente instalación es la que tenia: " apt-get install android-tools-adb android-tools-fastboot "

Una ultima razón es que la herramienta no quedara hasta el punto que esta hoy. Gradualmente irán creciendo sus funcionalidades. como por ejemplo una opción de hacer el root y pasar las gapps sin necesidad de usar cable USB, Instalación multiple (APK), entre otros.

---

2) ¿Usar una versión de adb desde la herramienta podría generar conflictos?
Para evitar eso el script tiene Macro variables globales para ADB y FASTBOOT de esta manera permite solo trabajar con los comandos adb de la herramienta y no con los del sistema (para llamar cada comando el script lo hace en mayúsculas $ADB $FASTBOOT y hace referencia a la ubicación de platform tools en la raíz del proyecto)

---

3) También existimos los usuarios de distros de 64 bits sin soporte instalado para correr binarios de 32 (solo instala cualquier Debian/Ubuntu reciente para un buen ejemplo), 

Por alguna razón no tome en cuenta esto y es un punto critico como mencionas. pero prefiero hacer uso de un platform tool x64 en el directorio raiz del proyecto y luego verificar el tipo de sistema donde se esta trabajando mediante "uname --all" o algo por el estilo y seleccionar el ADB Y FASTBOOT a utilizar.

---

4)Solo son dos modelos (desconozco las diferencias básicas entre ambos, no me he puesto a verlos a fondo, ya después tendré tiempo para eso), asi que asumo que los IDs USB han de ser los mismos - en este caso podrías sugerir un 51-android.rules predeterminado.

Haciendo varias pruebas pude notar que usando la misma tablet con diferentes cables usb el idProduct tienen a variar en mi caso con una TR10CS1 cambio de 016a por 015a algo así. Esto me quito la idea de dejar un 51-android.rules predeterminado y tratándose de un archivo de sistema que antes de usar la herramienta podría estar el resultado seria conflictos para la pc o el usuario.

Por lo contrario tengo la idea de tomar el 51-android.rules (si existe) y dejarlo como un backup mientras se ejecuta la herramienta y crear un nuevo 51-android.rules que contenga los id de los dispositivos conectados más los que ya estaban en el que se toma como backup en caso de que existiera el archivo (tomando los que encontró en el momento de ejecutar TR10-TOOL y trabajando con el comando sed y el comando grep) luego se podría destruir el 51-android.rules creado en tiempo de ejecución y puesto de vuelta en producción el viejo. Esto con el fin de contar con un "auto detector" de dispositivo. 

Al final del cuento quiero realizar una herramienta para gestionar android (cualquier modelo) y que lo reconozca automáticamente para realizar las tareas que ya la TR10-TOOL hace (con algunos root de dispositivos ya conocidos como samsung llamando las librerias remotas con "wget") más tareas comunes como respaldar contactos, copiar archivos, entre otros. Por lo que trato de ir dejando el camino abierto en el desarrollo para que migrar a la versión gráfica con todo esto no sea un problema

---

Si te quedaste a leer todo ese mamotreto que escribí de ante mano te doy gracias por usar la herramienta y por tus recomendaciones. Es el primer script que creo, si vez el código podrás notar que no soy muy experimentado en el tema y estoy contento de que pueda solucionar y ayudar a personas con esto.

**Comment by dilworks** [comment]
Interesantes puntos.

En comparacion con la otra opcion (aquel script modificado que alguien saco de XDA-Developers y que es solo para Windows), me quedo con la tuya - para ser un primer intento no esta nada mal.

Me puse a comparar las dos tabletas a ver las diferencias, y puedo sacar estas notas:
- La manera fácil de diferenciarlas a simple vista: solo destapa el área donde están los puertos - en la RS1 es blanca y en la CS1 es negra
- La CS1 usa un procesador Clover Trail (Atom Z2520), levantando desde una BIOS SFI (Simple Firmware Interface, un invento raro de Intel para sus tabletas), mientras que la RS1 parece ser mas poderosa: Bay Trail (Atom Z3735F) de 64 BITS (!!!), y BIOS UEFI (en teoría podría instalarsele Windows a esa cosa, si es que se sienten masoquistas, y debe existir alguna forma de accesar al programa de configuracion de la BIOS Phoenix que usa este equipo - lo mas lejos que he llegado es a un "Entering DnX mode" -tras rootearla y todo eso- del cual solo se puede salir apagando la tableta, al intentar prenderla en modo recovery -PWR+VOL UP-). Del resto las especificaciones son exactamente las mismas.
- Los IDs USB en efecto cambian cuando las tabletas pasan a modo bootloader/fastboot - llegue a ver un arroz-con-mango de 09ee/09ef/0a16/0a5f... e incluso un VID completamente distinto al de Intel en una ocasión! (18d1/fec0). Supongo que dependerán del modo en que arranquen y otras cosas. Imagino entonces que el archivo .rules solo serviría a propositos de "kickstart" para las labores iniciales, a menos que alguien se siente a capturar todos los IDs que puede generar cada modelo...

Con respecto a lo de adb, sugeriría entonces ofrecer algún switch/variable de entorno que puedas pasar al script, donde el usuario decide irse por el camino facil (usar el adb interno), o usar el que ya este instalado en la distro (si el usuario sabe lo que esta haciendo) - digamos un --use-system-platform-tools.

**Comment by neocarvajal** [comment]
Bueno con lo de adb seria de evaluar, por que entre fácil o difícil no hay diferencia (para el usuario) ya que todo lo haría internamente el script sin que el usuario lo notara a menos que un "echo" le avise (seleccionar SDK x86 o x64 y usarlo sin chocar con algún adb instalado previamente en el sistema). 

Gracias a tu recomendaciones es que le agregare el soporte para x64 y me toca modificar varias cosas en el script (esta madrugada toca trabajo)

En cuanto a los equipos hay un tercer modelo (TR10CD1 las malas lenguas dicen que han entregado de esas en otros estados). Tienes razón de las tablet que ha tocado revisar, la TR10RS1 es la más decente.

Aquí un poco de info : http://www.intel.com/support/education/solutions/tablets/sb/CS-034728.htm

---

Con el archivo .rules no me gusta la idea de tener un archivo con todos los id posibles. prefiero que se genere una regla dependiendo de que equipo se conecte a la pc cuando el script se ejecuta.

todo esto aun no lo termino apenas estoy pensando eso para terminar de subir la opción multiflash y así poder hacer todo el proceso en más de un equipo a la vez.

**Comment by dilworks** [comment]
Bueno, ciertamente el unico ID de dispositivo que realmente interesa es el inicial, es decir, el de una tableta fresca recien conectada por ADB. Quizas tambien importe el ID estando en modo Droidboot.

En fin, me puse a jugar con la CS1, y saque estos IDs:

```
USB-MTP: idVendor=8087, idProduct=0a15
[26970.645537] usb 3-1.2: Product: Android
[26970.645540] usb 3-1.2: Manufacturer: Android
[26970.645544] usb 3-1.2: SerialNumber: EF4A2303940

USB-ADB: idVendor=8087, idProduct=0a16
[27051.831838] usb 3-1.2: Product: Android
[27051.831886] usb 3-1.2: Manufacturer: Android
[27051.831892] usb 3-1.2: SerialNumber: EF4A2303940

DROIDBOOT: idVendor=8086, idProduct=09ee
[29402.190035] usb 3-1.2: Product: CLOVERVIEW
[29402.190037] usb 3-1.2: Manufacturer: INTEL
[29402.190038] usb 3-1.2: SerialNumber: 8555300E118C1FB7

TWRP: idVendor=8087, idProduct=09ef
[29418.018777] usb 3-1.2: Product: Android-Phone
[29418.018779] usb 3-1.2: Manufacturer: Android
[29418.018781] usb 3-1.2: SerialNumber: EF4A2303940

TWRP_FLASH: idVendor=18d1, idProduct=fec0
[29460.001344] usb 3-1.2: Product: Android-Phone
[29460.001358] usb 3-1.2: Manufacturer: Android
[29460.001360] usb 3-1.2: SerialNumber: EF4A2303940
```
- USB-MTP: tableta conectada en modo MTP, sin activar depuración USB
- USB-ADB: tableta conectada en modo ADB, depuración USB activada <= este es el modo que queremos
- DROIDBOOT: tableta en modo Droidboot/bootloader. Nótese que el VID es 8086, que es el VID viejo de Intel <= también nos interesa este?
- TWRP: creo que se explica por si solo
- TWRP_FLASH: este VID de Google me salio mientras TWRP flasheaba Super Su y el paquete de OpenGapps... curioso, cuando menos

**Comment by neocarvajal** [comment]
Valla que si jugaste con la tablet. La verdad no se si el viejo de intel sea necesario, sera que varia mucho entre cada modelo ?

**Comment by neocarvajal** [comment]
Si quieres puedes preparar el 51-android.rules con las reglas pre-cargadas y aquí haria que el script lo ponga en uso en tiempo de ejecución !

**Comment by wuilmerbolivar** [comment]
Mejoras aceptadas y pensadas en ser implementadas en futuras versiones! Gracias.
